if:
	clisp gpp_interpreter.lisp Test/if.txt

void:
	clisp gpp_interpreter.lisp Test/void_function.txt

one:
	clisp gpp_interpreter.lisp Test/one_parameter.txt

two:	
	clisp gpp_interpreter.lisp Test/two_parameter.txt

basic:
	clisp gpp_interpreter.lisp Test/basic.txt

complicate: 
	clisp gpp_interpreter.lisp Test/complicate.txt